### ISSUE TITLE
how can we make a request through curl as we do in php (to this module)

### ISSUE THREAD

**Issue by ankitverma2211** [agendor/sample-hapi-rest-api#4]
I am trying the following command : 
curl --data "username=user1@customer1.com&password=123" http://localhost:8000/tasks

Am I missing something or doing it entirely incorrectly

**Comment by tuliomonteazul** [comment]
The way you tried, it's sending username and password as post parameters and not as a header (as the server expected).
Try this way:
`curl -u "user1@customer1.com:123" http://localhost:8000/tasks`

This is gonna convert username and password to Base64 and send it as `Authorization` header, as the server expect. (You can add a `-v` option to see the sent headers)

Reference: [cURL manpage](http://curl.haxx.se/docs/manpage.html)
